// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7LuaD-89LJUhuwBtB0gQ-NtH8GgHDzJ8',
    appId: '1:230905539569:web:27912d8c9ea1be07507250',
    messagingSenderId: '230905539569',
    projectId: 'my-uber-d147e',
    authDomain: 'my-uber-d147e.firebaseapp.com',
    databaseURL: 'https://my-uber-d147e-default-rtdb.firebaseio.com',
    storageBucket: 'my-uber-d147e.appspot.com',
    measurementId: 'G-CM9SWQGMSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa7to4bTBYvvHOuJel42aFm3bS-Oc1jhA',
    appId: '1:230905539569:android:d775e837b0d26bb2507250',
    messagingSenderId: '230905539569',
    projectId: 'my-uber-d147e',
    databaseURL: 'https://my-uber-d147e-default-rtdb.firebaseio.com',
    storageBucket: 'my-uber-d147e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy19tJmN7aTvlCQJTTa0BlwpPx1xanMWk',
    appId: '1:230905539569:ios:2fc7379fc472e4c1507250',
    messagingSenderId: '230905539569',
    projectId: 'my-uber-d147e',
    databaseURL: 'https://my-uber-d147e-default-rtdb.firebaseio.com',
    storageBucket: 'my-uber-d147e.appspot.com',
    androidClientId: '230905539569-u4d673f5lulu695vrpdjkgin2n0fem5c.apps.googleusercontent.com',
    iosClientId: '230905539569-s1g3jkaht0ls43tffg2jr2gtf7217s3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy19tJmN7aTvlCQJTTa0BlwpPx1xanMWk',
    appId: '1:230905539569:ios:2fc7379fc472e4c1507250',
    messagingSenderId: '230905539569',
    projectId: 'my-uber-d147e',
    databaseURL: 'https://my-uber-d147e-default-rtdb.firebaseio.com',
    storageBucket: 'my-uber-d147e.appspot.com',
    androidClientId: '230905539569-u4d673f5lulu695vrpdjkgin2n0fem5c.apps.googleusercontent.com',
    iosClientId: '230905539569-s1g3jkaht0ls43tffg2jr2gtf7217s3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxi',
  );
}
